name: Run Bash Script
on: [push]
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      # you must first checkout the code before you can execute it.
      # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
      - uses: actions/checkout@v2
      - name: Run Build Script
        run: bash ./.github/scripts/build.sh
        shell: bash
      - run: node ./say-hello.js
  # read a file
  Reads-File:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cat say-hello.js
