name: Run Bash Script
on: [push]
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      # you must first checkout the code before you can execute it.
      - uses: actions/checkout@v2
      - name: Run Build Script
        run: bash ./.github/build.sh
        shell: bash
      - run: node ./say-hello.js
      - run: cat say-hello.js
